version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_admin_password
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:

