version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfile1
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
      - "2222:22"  # SSH 포트 개방
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:

